// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: task/msg.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg_Type int32

const (
	// 指定用户消息
	Msg_SEND Msg_Type = 0
	// 广播消息
	Msg_BROADCAST Msg_Type = 1
	// 主动关闭客户端连接
	Msg_CLOSE Msg_Type = 2
	// 历史消息
	Msg_History Msg_Type = 3
)

// Enum value maps for Msg_Type.
var (
	Msg_Type_name = map[int32]string{
		0: "SEND",
		1: "BROADCAST",
		2: "CLOSE",
		3: "History",
	}
	Msg_Type_value = map[string]int32{
		"SEND":      0,
		"BROADCAST": 1,
		"CLOSE":     2,
		"History":   3,
	}
)

func (x Msg_Type) Enum() *Msg_Type {
	p := new(Msg_Type)
	*p = x
	return p
}

func (x Msg_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Msg_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_task_msg_proto_enumTypes[0].Descriptor()
}

func (Msg_Type) Type() protoreflect.EnumType {
	return &file_task_msg_proto_enumTypes[0]
}

func (x Msg_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Msg_Type.Descriptor instead.
func (Msg_Type) EnumDescriptor() ([]byte, []int) {
	return file_task_msg_proto_rawDescGZIP(), []int{0, 0}
}

// 消息格式
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Msg_Type `protobuf:"varint,1,opt,name=type,proto3,enum=task.Msg_Type" json:"type,omitempty"` //发送类型
	Server    string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`                 //用户所在服务器id
	Event     string   `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`                   //消息类型
	UserIds   []int64  `protobuf:"varint,4,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	Timestamp int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body      []byte   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_task_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_task_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_task_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() Msg_Type {
	if x != nil {
		return x.Type
	}
	return Msg_SEND
}

func (x *Msg) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Msg) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Msg) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Msg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Msg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_task_msg_proto protoreflect.FileDescriptor

var file_task_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x61, 0x73, 0x6b, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0xdc, 0x01, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x22,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x74,
	0x61, 0x73, 0x6b, 0x2e, 0x4d, 0x73, 0x67, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x37, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x42, 0x52, 0x4f, 0x41, 0x44, 0x43, 0x41, 0x53, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x10, 0x03, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_task_msg_proto_rawDescOnce sync.Once
	file_task_msg_proto_rawDescData = file_task_msg_proto_rawDesc
)

func file_task_msg_proto_rawDescGZIP() []byte {
	file_task_msg_proto_rawDescOnce.Do(func() {
		file_task_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_task_msg_proto_rawDescData)
	})
	return file_task_msg_proto_rawDescData
}

var file_task_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_task_msg_proto_goTypes = []interface{}{
	(Msg_Type)(0), // 0: task.Msg.Type
	(*Msg)(nil),   // 1: task.Msg
}
var file_task_msg_proto_depIdxs = []int32{
	0, // 0: task.Msg.type:type_name -> task.Msg.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_task_msg_proto_init() }
func file_task_msg_proto_init() {
	if File_task_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_task_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_task_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_msg_proto_goTypes,
		DependencyIndexes: file_task_msg_proto_depIdxs,
		EnumInfos:         file_task_msg_proto_enumTypes,
		MessageInfos:      file_task_msg_proto_msgTypes,
	}.Build()
	File_task_msg_proto = out.File
	file_task_msg_proto_rawDesc = nil
	file_task_msg_proto_goTypes = nil
	file_task_msg_proto_depIdxs = nil
}
