{
 "title": "chat_logic",
 "tags": [
  "Chat",
  "Logic"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(chat_http_request_count_total, job)"
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "label_values(chat_http_request_count_total{endpoint!~\"/metrics\", status!=\"404\", job=~\"$job\"}, endpoint)"
   },
   {
    "name": "method",
    "label": "Method",
    "query": "label_values(chat_http_request_count_total, method)"
   },
   {
    "name": "status",
    "label": "Status",
    "query": "label_values(chat_http_request_count_total, status)"
   },
   { "name": "quantile", "label": "Quantile", "query": "0.95,0.75,0.25" }
  ]
 },
 "panels": [
  {
   "title": "Chat last updated",
   "type": "singlestat",
   "description": "应用开启时间",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - chat_uptime{job=~\"$job\"}) * 1000"
    }
   ]
  },
  {
   "title": "Requests QPS",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(chat_http_request_count_total{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Chat Uptime",
   "type": "singlestat",
   "description": "应用运行时长",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "chat_uptime{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Quantile of requests",
   "type": "graph",
   "description": "取 $quantile% 样本  在 $interval 分钟内的 http 请求数的平均增长速率总和",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantile, sum(rate(chat_http_request_duration_seconds_bucket{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])) by (le))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Duration per request",
   "type": "graph",
   "description": "每个请求平均响应时间",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(chat_http_request_duration_seconds_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\r\n/\r\nrate(chat_http_request_duration_seconds_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Response size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(chat_http_response_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(chat_http_response_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request size(bytes) per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(chat_http_request_size_bytes_sum{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])\n/\nrate(chat_http_request_size_bytes_count{job=~\"$job\", endpoint=~\"$endpoint\", method=~\"$method\", status=~\"$status\"}[$interval])",
     "legendFormat": "{{ endpoint }}-{{method}}-{{status}}"
    }
   ]
  }
 ]
}