app:
  Name: mall
  Mode: debug                 # 开发模式, debug, release, test
  DfsUrl: http://127.0.0.1:9000
  JwtSecret: Your-Jwt-Secret
  JwtTimeout: 86400           # jwt有效时间, 单位秒
  CtxDefaultTimeout: 12s
  Debug: true
  Env: dev
  MaxLimit: 1000
  IPLimit: 100
  IPLimitExpr: 5m
eth:
  NetworkUrl: ws://localhost:8546  #网络地址，要监听 event 必须使用 ws
  NetworkID: 15
http:
  Port: 9052
  ReadTimeout: 5s
  WriteTimeout: 5s
mysql:
  Name: mall                      # 数据库名称
  Addr: 127.0.0.1:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: 123456
  TablePrefix: ""                   # 表前缀
  Debug: true                       # 是否开启调试，打印所有sql
  MaxIdleConn: 10                   # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 100                  # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60m              # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些
redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
  MinIdleConn: 30
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 500
  PoolTimeout: 240
logger:
  Development: false
  DisableCaller: false
  Encoding: json                          # json or console
  Level: INFO                             # 日志级别，DEBUG, INFO, WARN, ERROR, FATAL
  Name: mall                              # 应用名称
  Writers: file                           # 有2个可选项：file,console 选择file会将日志记录到logger_file指定的日志文件中，选择console会将日志输出到标准输出，当然也可以两者同时选择
  LoggerFile: ./logs/mall.log             # 日志文件
  LoggerWarnFile: ./logs/mall.warn.log
  LoggerErrorFile: ./logs/mall.err.log