app:
  JwtSecret: UCAYyw9S5Q9oS2Bh1GhXZZmOawfiGSZXbuYR6KcYvidfhoGOcwsk8zb7vwpsd37o
  DfsUrl: http://192.168.8.76:9000
  Debug: true
eth:
  NetworkUrl: ws://localhost:8546  #网络地址，要监听 event 必须使用 ws
  NetworkID: 15
mysql:
  Name: mall                     # 数据库名称
  Addr: 192.168.8.76:3306        # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: 123456
redis:
  Addr: 192.168.8.76:6379
  Password: ""
logger:
  Level: DEBUG
  Writers: console