name: chat.logic
mode: debug                 # 开发模式, debug, release, test
jwtSecret: Your-Jwt-Secret
jwtTimeout: 86400           # jwt有效时间, 单位秒
debug: true
registryAddress: 127.0.0.1:8500
brokerAddress: nats://127.0.0.1:4222
tracerAddress:
http:
  Port: :9050
  ReadTimeout: 5s
  WriteTimeout: 5s
grpc:
  Network: tcp
  Port: 20007
  ReadTimeout: 5s
  WriteTimeout: 5s
mysql:
  Name: chat                      # 数据库名称
  Addr: 127.0.0.1:3306            # 如果是 docker,可以替换为 对应的服务名称，eg: db:3306
  UserName: root
  Password: 123456
  TablePrefix: ""                   # 表前缀
  Debug: true                       # 是否开启调试，打印所有sql
  MaxIdleConn: 10                   # 最大闲置的连接数，0意味着使用默认的大小2， 小于0表示不使用连接池
  MaxOpenConn: 100                  # 最大打开的连接数, 需要小于数据库配置中的max_connections数
  ConnMaxLifeTime: 60               # 单个连接最大存活时间，建议设置比数据库超时时长(wait_timeout)稍小一些
redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
  MinIdleConn: 30
  DialTimeout: 60
  ReadTimeout: 3
  WriteTimeout: 3
  PoolSize: 500
  PoolTimeout: 240
minio:
  Endpoint: 127.0.0.1:9000
  AccessID: minioadmin
  SecretAccess: minioadmin
  Bucket: group1
  Region: us-east-1